# PBS configuration
queue: express
project: x77
walltime: 0:30:00
jobname: 1deg_jra55_ryf
ncpus: 304

shortpath: /short/e14

# Model configuration
model: access-om2
submodels:
    - name: coupler
      model: oasis
      input: oasis_jra55_to_1deg
      ncpus: 0

    - name: atmosphere
      model: matm
      exe: matm_jra55_fd6f3f8a.exe
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM_c830597c.x
      input: mom_1deg
      ncpus: 240

    - name: ice
      model: cice5
      exe: cice_auscom_360x300_24p_1c1f7c75.exe
      input: cice_1deg
      ncpus: 24

calendar:
    runtime:
        years: 0
        months: 1
        days: 0

    start:
        year: 1
        month: 1
        days: 1

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread
