# PBS configuration
queue: express
project: e14
walltime: 0:30:00
jobname: 1deg_jra55_ryf
ncpus: 256

shortpath: /short/e14

# Model configuration
model: access-om2
submodels:
    - name: coupler
      model: oasis
      input: oasis_jra55_to_1deg
      ncpus: 0

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM_30e2c57f.x
      input: mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: cice_auscom_360x300_24p_05597824.exe
      input: cice_1deg
      ncpus: 24

    - name: atmosphere
      model: matm
      exe: matm_jra55_ad57636f.exe
      ncpus: 1

calendar:
    runtime:
        years: 0
        months: 0
        days: 1

    start:
        year: 1
        month: 1
        days: 1

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0 --mca btl_openib_eager_limit 4096 --mca btl_openib_max_send_size 8192 --mca mtl mxm
qsub_flags: -lother=hyperthread
