# PBS configuration
queue: normal
project: x77
walltime: 5:00:00
jobname: 1deg_jra55_ryf
ncpus: 304

shortpath: /short/e14

# Model configuration
model: access
submodels:
    - name: coupler
      model: oasis
      input: oasis_jra55_to_1deg
      ncpus: 0

    - name: atmosphere
      model: matm
      exe: matm_jra55.exe
      input: jra55_ryf
      ncpus: 1

    - name: ocean
      model: mom
      exe: fms_ACCESS-OM_11b63cb3.x
      input: mom_1deg
      ncpus: 240

    - name: ice
      model: cice5
      exe: cice_auscom_360x300_24p.exe
      input: cice_1deg
      ncpus: 24

calendar:
    runtime:
        years: 10
        months: 0
        days: 0

    start:
        year: 1
        month: 1
        days: 1

# Misc
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -lother=hyperthread
